# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b50e5caa9a37578a5e97108b096a57d41809a2e2da124ecbf41cdc18b3deec11218688e60692713477212dd21d1924899ebe7b8fe1d9f752185ae797a621d4a4

test:
  secret_key_base: 3b794add2c7ff4d7188d60b17e163b081de4e91155729fb1a9547a4e66e211c888170d74d4da97748846b175b18e2619259c9994bf7c314c617a7d4229841e41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
